function jsonResponse(body, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'POST, OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type' } });
}
async function parseBody(request) {
  const contentType = request.headers.get('content-type') || '';
  if (contentType.includes('application/json')) return await request.json();
  if (contentType.includes('application/x-www-form-urlencoded') || contentType.includes('multipart/form-data')) { const form = await request.formData(); return Object.fromEntries(form.entries()); }
  const text = await request.text(); try { return JSON.parse(text || '{}'); } catch { return { mensaje: text }; }
}
function pick(...vals) { for (const v of vals) if (v !== undefined && v !== null && String(v).trim() !== '') return String(v).trim(); return ''; }
function clip(s, n = 240) { s = String(s || '').replace(/\s+/g, ' ').trim(); return s.length > n ? s.slice(0, n) + '…' : s; }
function fmtPhone(s) { let d = String(s || '').replace(/\D/g, ''); if (d.startsWith('34') && d.length >= 11) d = d.slice(2); return /^[6789]\d{8}$/.test(d) ? d : String(s || '').trim(); }
function prettyPhone(s) { return String(s || '').replace(/^(\d{3})(\d{3})(\d{3})$/, '$1 $2 $3'); }
function normalizeReforma(s) { const value = String(s || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, ''); if (value.includes('bano')) return 'baño'; if (value.includes('cocina')) return 'cocina'; if (value.includes('integral')) return 'integral'; if (value.includes('ducha') || value.includes('banera')) return 'baño'; if (value.includes('pintura')) return 'pintura'; if (value.includes('suelo')) return 'suelos'; if (value.includes('local')) return 'local'; return value.replace(/^reforma\s+(de\s+)?/, '').trim() || 'reformas'; }
async function refreshGoogleToken(env) { const body = new URLSearchParams({ client_id: env.GOOGLE_CLIENT_ID, client_secret: env.GOOGLE_CLIENT_SECRET, refresh_token: env.GOOGLE_REFRESH_TOKEN, grant_type: 'refresh_token' }); const res = await fetch('https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body }); if (!res.ok) throw new Error(`google_oauth_${res.status}`); return (await res.json()).access_token; }
async function appendSheet(env, row) { const token = await refreshGoogleToken(env); const url = `https://sheets.googleapis.com/v4/spreadsheets/${env.GOOGLE_SHEET_ID}/values/Leads!A%3AK:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`; const res = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ values: [row] }) }); const data = await res.json().catch(() => ({})); if (!res.ok) throw new Error(`sheet_${res.status}_${JSON.stringify(data).slice(0, 200)}`); return data; }
async function sendTelegram(env, text) { const res = await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendMessage`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ chat_id: env.TELEGRAM_CHAT_ID, message_thread_id: Number(env.TELEGRAM_THREAD_ID || 4), text, disable_web_page_preview: true }) }); const data = await res.json().catch(() => ({})); if (!res.ok || data.ok === false) throw new Error(`telegram_${res.status}_${JSON.stringify(data).slice(0, 200)}`); return data; }
async function sendGestiona(env, lead) { const res = await fetch(env.GESTIONA_WEB_URL, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Accept': 'application/json' }, body: JSON.stringify(lead) }); const text = await res.text().catch(() => ''); let data; try { data = JSON.parse(text || '{}'); } catch { data = { raw: text.slice(0, 500) }; } if (!res.ok || data.ok === false) throw new Error(`gestiona_${res.status}_${JSON.stringify(data).slice(0, 500)}`); return { status: res.status, data }; }
export async function onRequestOptions() { return jsonResponse({ ok: true }); }
export async function onRequestPost({ request, env }) { try { const body = await parseBody(request); const nowIso = new Date().toISOString(); const referer = request.headers.get('referer') || ''; const web = pick(body.web, body.website, body.dominio) || 'reformaseldasanchis.es'; const canal = 'formulario'; const fuente = 'Web'; const nombre = pick(body.nombre, body.name); const telefono = fmtPhone(pick(body.telefono, body.phone)); const email = pick(body.email, body.correo); const poblacion = pick(body.localidad, body.poblacion, body.zona, body.city) || 'Elda'; const proyecto = pick(body.servicio, body.tipo, body.tipo_proyecto, body.project_type) || 'Solicitud de reforma'; const metros = pick(body.metros, body.superficie); const mensaje = pick(body.mensaje, body.detalles, body.message); const pagina = pick(body.pagina, body.page, body.url, body.referrer, referer); const id = pick(body.submission_id, body.call_id, body.id) || `form-${Date.now()}`; const detalles = [email ? `Email: ${email}` : '', metros ? `Superficie: ${metros}` : '', mensaje || '', pagina ? `Página: ${pagina}` : ''].filter(Boolean).join('\n') || 'Sin detalles'; const sheetUrl = `https://docs.google.com/spreadsheets/d/${env.GOOGLE_SHEET_ID}/edit?usp=sharing`; const telegramText = `NUEVO LEAD: ${web}\n\n` + `👤 Nombre: ${nombre || 'No indicado'}\n` + (email ? `✉️ Email: ${email}\n` : '') + `📍 Zona: ${poblacion}\n` + `🧩 Proyecto: ${proyecto}\n` + (metros ? `📐 Superficie: ${metros}\n` : '') + `📝 Detalles: ${clip(mensaje || detalles)}\n` + `📞 Teléfono: ${prettyPhone(telefono) || 'No indicado'}\n` + `- Web: ${web}\n` + `- Canal: ${canal}\n` + `- ID: ${id}\n` + `- Guardado en Google Sheet: ${sheetUrl}\n\n` + `————————————————`; const row = [nowIso, web, canal, fuente, nombre, prettyPhone(telefono), poblacion, proyecto, detalles, id, '']; const crmPayload = { detalles: `${detalles || 'Solicitud de presupuesto desde formulario web.'}\n\nFicha de Google Maps: https://maps.app.goo.gl/T6eZUzW9SRNYGu8W8`, poblacion, telefono, nombre, tipo_reforma: normalizeReforma(proyecto), hora: new Date().toLocaleTimeString('es-ES', { hour: '2-digit', minute: '2-digit', timeZone: 'Europe/Madrid' }) }; const [crm, sheet, telegram] = await Promise.allSettled([sendGestiona(env, crmPayload), appendSheet(env, row), sendTelegram(env, telegramText)]); const results = { crm: crm.status, sheet: sheet.status, telegram: telegram.status }; const errors = [crm, sheet, telegram].filter(r => r.status === 'rejected').map(r => String(r.reason && r.reason.message ? r.reason.message : r.reason)); if (errors.length) return jsonResponse({ ok: false, id, results, errors }, 502); return jsonResponse({ ok: true, id, results }); } catch (error) { return jsonResponse({ ok: false, error: 'form_handler_error', message: String(error && error.message ? error.message : error) }, 500); } }
export async function onRequestGet() { return jsonResponse({ ok: false, error: 'method_not_allowed' }, 405); }
